// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
namespace MyStruct {
class SESSION;
struct SESSIONDefaultTypeInternal;
extern SESSIONDefaultTypeInternal _SESSION_default_instance_;
}  // namespace MyStruct
PROTOBUF_NAMESPACE_OPEN
template<> ::MyStruct::SESSION* Arena::CreateMaybeMessage<::MyStruct::SESSION>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace MyStruct {

// ===================================================================

class SESSION final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyStruct.SESSION) */ {
 public:
  inline SESSION() : SESSION(nullptr) {}
  ~SESSION() override;
  explicit PROTOBUF_CONSTEXPR SESSION(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SESSION(const SESSION& from);
  SESSION(SESSION&& from) noexcept
    : SESSION() {
    *this = ::std::move(from);
  }

  inline SESSION& operator=(const SESSION& from) {
    CopyFrom(from);
    return *this;
  }
  inline SESSION& operator=(SESSION&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SESSION& default_instance() {
    return *internal_default_instance();
  }
  static inline const SESSION* internal_default_instance() {
    return reinterpret_cast<const SESSION*>(
               &_SESSION_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SESSION& a, SESSION& b) {
    a.Swap(&b);
  }
  inline void Swap(SESSION* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SESSION* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SESSION* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SESSION>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SESSION& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SESSION& from) {
    SESSION::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SESSION* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyStruct.SESSION";
  }
  protected:
  explicit SESSION(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLoginFlagFieldNumber = 1,
    kSocketFdFieldNumber = 2,
  };
  // required int32 login_flag = 1;
  bool has_login_flag() const;
  private:
  bool _internal_has_login_flag() const;
  public:
  void clear_login_flag();
  int32_t login_flag() const;
  void set_login_flag(int32_t value);
  private:
  int32_t _internal_login_flag() const;
  void _internal_set_login_flag(int32_t value);
  public:

  // required int32 socket_fd = 2;
  bool has_socket_fd() const;
  private:
  bool _internal_has_socket_fd() const;
  public:
  void clear_socket_fd();
  int32_t socket_fd() const;
  void set_socket_fd(int32_t value);
  private:
  int32_t _internal_socket_fd() const;
  void _internal_set_socket_fd(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:MyStruct.SESSION)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int32_t login_flag_;
    int32_t socket_fd_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SESSION

// required int32 login_flag = 1;
inline bool SESSION::_internal_has_login_flag() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SESSION::has_login_flag() const {
  return _internal_has_login_flag();
}
inline void SESSION::clear_login_flag() {
  _impl_.login_flag_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t SESSION::_internal_login_flag() const {
  return _impl_.login_flag_;
}
inline int32_t SESSION::login_flag() const {
  // @@protoc_insertion_point(field_get:MyStruct.SESSION.login_flag)
  return _internal_login_flag();
}
inline void SESSION::_internal_set_login_flag(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.login_flag_ = value;
}
inline void SESSION::set_login_flag(int32_t value) {
  _internal_set_login_flag(value);
  // @@protoc_insertion_point(field_set:MyStruct.SESSION.login_flag)
}

// required int32 socket_fd = 2;
inline bool SESSION::_internal_has_socket_fd() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SESSION::has_socket_fd() const {
  return _internal_has_socket_fd();
}
inline void SESSION::clear_socket_fd() {
  _impl_.socket_fd_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t SESSION::_internal_socket_fd() const {
  return _impl_.socket_fd_;
}
inline int32_t SESSION::socket_fd() const {
  // @@protoc_insertion_point(field_get:MyStruct.SESSION.socket_fd)
  return _internal_socket_fd();
}
inline void SESSION::_internal_set_socket_fd(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.socket_fd_ = value;
}
inline void SESSION::set_socket_fd(int32_t value) {
  _internal_set_socket_fd(value);
  // @@protoc_insertion_point(field_set:MyStruct.SESSION.socket_fd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MyStruct

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
