// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#include "msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace MyStruct {
PROTOBUF_CONSTEXPR SESSION::SESSION(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.login_flag_)*/0
  , /*decltype(_impl_.socket_fd_)*/0} {}
struct SESSIONDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SESSIONDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SESSIONDefaultTypeInternal() {}
  union {
    SESSION _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SESSIONDefaultTypeInternal _SESSION_default_instance_;
}  // namespace MyStruct
static ::_pb::Metadata file_level_metadata_msg_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_msg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_2eproto = nullptr;

const uint32_t TableStruct_msg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::MyStruct::SESSION, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::MyStruct::SESSION, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MyStruct::SESSION, _impl_.login_flag_),
  PROTOBUF_FIELD_OFFSET(::MyStruct::SESSION, _impl_.socket_fd_),
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::MyStruct::SESSION)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::MyStruct::_SESSION_default_instance_._instance,
};

const char descriptor_table_protodef_msg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tmsg.proto\022\010MyStruct\"0\n\007SESSION\022\022\n\nlogi"
  "n_flag\030\001 \002(\005\022\021\n\tsocket_fd\030\002 \002(\005"
  ;
static ::_pbi::once_flag descriptor_table_msg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_2eproto = {
    false, false, 71, descriptor_table_protodef_msg_2eproto,
    "msg.proto",
    &descriptor_table_msg_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_msg_2eproto::offsets,
    file_level_metadata_msg_2eproto, file_level_enum_descriptors_msg_2eproto,
    file_level_service_descriptors_msg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_2eproto_getter() {
  return &descriptor_table_msg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_2eproto(&descriptor_table_msg_2eproto);
namespace MyStruct {

// ===================================================================

class SESSION::_Internal {
 public:
  using HasBits = decltype(std::declval<SESSION>()._impl_._has_bits_);
  static void set_has_login_flag(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_socket_fd(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

SESSION::SESSION(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MyStruct.SESSION)
}
SESSION::SESSION(const SESSION& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SESSION* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.login_flag_){}
    , decltype(_impl_.socket_fd_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.login_flag_, &from._impl_.login_flag_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.socket_fd_) -
    reinterpret_cast<char*>(&_impl_.login_flag_)) + sizeof(_impl_.socket_fd_));
  // @@protoc_insertion_point(copy_constructor:MyStruct.SESSION)
}

inline void SESSION::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.login_flag_){0}
    , decltype(_impl_.socket_fd_){0}
  };
}

SESSION::~SESSION() {
  // @@protoc_insertion_point(destructor:MyStruct.SESSION)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SESSION::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SESSION::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SESSION::Clear() {
// @@protoc_insertion_point(message_clear_start:MyStruct.SESSION)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.login_flag_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.socket_fd_) -
        reinterpret_cast<char*>(&_impl_.login_flag_)) + sizeof(_impl_.socket_fd_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SESSION::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required int32 login_flag = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_login_flag(&has_bits);
          _impl_.login_flag_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required int32 socket_fd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_socket_fd(&has_bits);
          _impl_.socket_fd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SESSION::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyStruct.SESSION)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 login_flag = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_login_flag(), target);
  }

  // required int32 socket_fd = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_socket_fd(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyStruct.SESSION)
  return target;
}

size_t SESSION::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MyStruct.SESSION)
  size_t total_size = 0;

  if (_internal_has_login_flag()) {
    // required int32 login_flag = 1;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_login_flag());
  }

  if (_internal_has_socket_fd()) {
    // required int32 socket_fd = 2;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_socket_fd());
  }

  return total_size;
}
size_t SESSION::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyStruct.SESSION)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 login_flag = 1;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_login_flag());

    // required int32 socket_fd = 2;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_socket_fd());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SESSION::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SESSION::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SESSION::GetClassData() const { return &_class_data_; }


void SESSION::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SESSION*>(&to_msg);
  auto& from = static_cast<const SESSION&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyStruct.SESSION)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.login_flag_ = from._impl_.login_flag_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.socket_fd_ = from._impl_.socket_fd_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SESSION::CopyFrom(const SESSION& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyStruct.SESSION)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SESSION::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void SESSION::InternalSwap(SESSION* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SESSION, _impl_.socket_fd_)
      + sizeof(SESSION::_impl_.socket_fd_)
      - PROTOBUF_FIELD_OFFSET(SESSION, _impl_.login_flag_)>(
          reinterpret_cast<char*>(&_impl_.login_flag_),
          reinterpret_cast<char*>(&other->_impl_.login_flag_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SESSION::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_2eproto_getter, &descriptor_table_msg_2eproto_once,
      file_level_metadata_msg_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace MyStruct
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MyStruct::SESSION*
Arena::CreateMaybeMessage< ::MyStruct::SESSION >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyStruct::SESSION >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
